import cv2
# load it in GRAYSCALE color mode...
image1 = cv2.imread("""D:\Common\Programming\GitHub\PythonLearningGR\MyPrograms\OpenCV\OpenCV_logo.png""", 0)
image2 = cv2.imread("""D:\Common\Programming\GitHub\PythonLearningGR\MyPrograms\OpenCV\entomo.jpg""", 0)
cv2.imshow('Analytics Vidhya Computer Vision', image1)
cv2.imshow('Entomo', image2)
image3 = image2[0:300]
cv2.imshow('Sliced Entomo', image3)
cv2.waitKey()
cv2.destroyAllWindows()
print ("image1 properties are: ")
print (image1)
print ("image 1 size: ", image1.shape)
print ("image 1 type: ", type(image1))
print ("\n")
print ("image2 properties are: ")
print (image2)
print (image2[2, 1])
print ("image 2 size: ", image2.shape)
print ("image 2 size: ", image2.size)
#print ("image 2 type: ", type(image2))
print ("image 2 all properties are: ", dir(image1))
print ("\n")
print ("image3 properties are: ")
print (image3)
print ("image 3 size: ", image3.shape)
#print ("image 2 size: ", image3.size)
print ("image 3 type: ", type(image3))
